version: "3.7"
services: 
    nginx:
        image: nginx:1.17.10-alpine
        ports: 
            - "8080:80"
        volumes: 
            - ./src:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
    php:
        build: ./php
        ports: 
            - "9000:9000"
        volumes: 
            - ./src:/var/www/html
        depends_on: 
            - mysql
        links: 
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: compass
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        container_name: mysql
